# Generated by Django 4.0.1 on 2022-01-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='project',
            name='link_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='project',
            name='link_twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
