# Generated by Django 4.0.1 on 2022-01-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_link_facebook_project_link_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link_twitter',
        ),
    ]
