# Generated by Django 4.0.1 on 2022-01-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_link_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='crated',
            new_name='created',
        ),
    ]
