<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-01-27 04:16
=======
# Generated by Django 4.0.1 on 2022-01-24 04:17
>>>>>>> 7aa53a6dd013dc37f354cf930508aa4e74b902c0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_options_rename_crated_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='Project', verbose_name='Imagen'),
        ),
    ]
