# Generated by Django 4.0.1 on 2022-01-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_telefono', models.BigIntegerField(verbose_name='Número de telefono')),
                ('descripcion_tel', models.CharField(max_length=200, verbose_name='Pequeña descripción')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('descripcion_email', models.CharField(max_length=200, verbose_name='Pequeña descripción')),
                ('num_whatsapp', models.BigIntegerField(verbose_name='Número de Whatsapp')),
                ('descripcion_whatsapp', models.CharField(max_length=200, verbose_name='Pequeña descripción')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
