# Generated by Django 4.0.1 on 2022-01-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('parrafo_1', models.TextField(verbose_name='Primer Parrafo')),
                ('parrafo_2', models.TextField(verbose_name='Segundo Parrafo')),
                ('image', models.ImageField(upload_to='Proyect', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Acerca De',
                'verbose_name_plural': 'Acerca De',
            },
        ),
    ]
