# Generated by Django 4.0.1 on 2022-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_created_about_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='Proyect', verbose_name='Foto de Perfil'),
        ),
    ]
