# Generated by Django 4.0.1 on 2022-01-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('-created',), 'verbose_name': 'Acerca De', 'verbose_name_plural': 'Acerca De'},
        ),
    ]
