# Generated by Django 4.0.1 on 2022-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profesiones',
            field=models.CharField(max_length=50, null=True, verbose_name='Profesión'),
        ),
    ]
