# Generated by Django 4.0.1 on 2022-01-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_profesiones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profesiones',
            new_name='profesion',
        ),
    ]
