# Generated by Django 4.0.1 on 2022-01-27 05:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_profesiones_about_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='parrafo_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='parrafo_2',
        ),
        migrations.AddField(
            model_name='about',
            name='parrafo',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Parrafos'),
        ),
    ]
